Examen3/Controllers/AutoController.cs
using DDD.Entidades;
using DDD.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Examen3.Controllers
{
    public class AutoController : Controller
    {
        // Definir un Manager
        ManagerAuto mngAuto = new ManagerAuto();
        ManagerMarca mngMarca = new ManagerMarca();
        // GET: Auto
        public ActionResult Index()
		{
            return View();
		}

        public ActionResult ListarAutos()
		{
            return View(mngAuto.Listar());
		}


        public ActionResult RegistrarAuto()
		{
            ViewBag.marcas = mngMarca.Listar();
            return View(new Auto());
		}


        [HttpPost]
        public ActionResult RegistrarAuto(Auto a)
		{
			if (!ModelState.IsValid)
			{
                ViewBag.marcas = mngMarca.Listar();
                return View(a);
			}
			else
			{
                mngAuto.Insertar(a);
                return RedirectToAction("ListarAutos");
			}
		}
        public ActionResult EditarAuto(int id)
		{
            Auto a = mngAuto.Obtener(id);
            ViewBag.marcas = mngMarca.Listar();
            return View(a);
		}

        [HttpPost]
        public ActionResult EditarAuto(Auto a)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.marcas = mngMarca.Listar();
                return View(a);
            }
            else
            {
                mngAuto.Actualizar(a);
                return RedirectToAction("ListarAutos");
            }
        }

        public ActionResult VerAuto(int id)
		{
            return View(mngAuto.Obtener(id));
		}


        public ActionResult EliminarAuto(int id)
        {
            Auto a = mngAuto.Obtener(id);
            return View(a);
        }

        [HttpPost]
        public ActionResult EliminarAuto(Auto a)
        {

                mngAuto.Eliminar(a.idAuto);
                return RedirectToAction("ListarAutos");
        }


    }
}

Examen3/Controllers/ReporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

// Importar
using Microsoft.Reporting.WebForms;
using Examen3.DataSets;
using Examen3.Models;

namespace Examen3.Controllers
{
    public class ReporteController : Controller
    {
        // GET: Reporte de lista de Autos
        public ActionResult ReporteAutos()
        {
            // Visor del Reporte
            ReportViewer rvw = new ReportViewer();
            rvw.ProcessingMode = ProcessingMode.Local;
            rvw.SizeToReportContent = true;
            // Indicar el nombre del reporte a mostrar en el visor
            rvw.LocalReport.ReportPath = Request.MapPath(Request.ApplicationPath) + @"Reportes\RptAutos.rdlc";
            // Asignamos la fuente de datos
            // 1. Importamos el modelo de datos
            BD_CL3Entities bd = new BD_CL3Entities();
            // 2. Asigna los datos de la tabla autos al Dataset que el reporte espera
            rvw.LocalReport.DataSources.Add(new ReportDataSource("DataSetAutos", bd.Vehiculo));
            // 3. Si el reporte tiene hipervinculos
            rvw.LocalReport.EnableHyperlinks = true;
            // Pasamos el visor al viewbag para que se muestre en la vista
            ViewBag.visor = rvw;

            return View();
        }
    }
}

Examen3/Views/General/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>POOII - Examen 2</title>
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	@Styles.Render("~/Content/css")
</head>
<body>
	<div class="page">
		<span class="menu_toggle text-white">
			<i class="menu_open fa fa-bars fa-lg"></i>
			<i class="menu_close fa fa-times fa-lg"></i>
		</span>
		<ul class="menu_items">
			<li>
				<a href="@Url.Action("Index", "Auto")">
					<i class="icon fa fa-home"></i>
					Inicio
				</a>
			</li>
			<li>
				<a href="@Url.Action("ListarAutos", "Auto")">
					<i class="icon fa fa-car"></i>
					AUTOS
				</a>
			</li>
			<li>
				<a href="@Url.Action("ReporteAutos", "Reporte")">
					<i class="icon fa fa-list"></i>
					Reportes
				</a>
			</li>
		</ul>
		<main class="content">
			<div class="content_inner">
				@RenderBody()
			</div>

		</main>

		<footer class="footer bg-dark p-3 text-center">
			<p class="h5 mb-0">Made by &copy;<a href="https://juliorivera.dev" target="_blank" rel="noopener noreferrer" class="text-white">Julio Cesar Rivera</a></p>
		</footer>
	</div>
	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>



	@Scripts.Render("~/bundles/app")
	@RenderSection("scripts", required: false)


</body>
</html>